// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHeaderNav,
  DefaultHeaderNavProps,
} from "../plasmic/amap_website/PlasmicHeaderNav";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { DesktopMenu } from "./DesktopMenu";
import clsx from "clsx";
import { MobileMenu } from "./MobileMenu";

export interface HeaderNavProps extends DefaultHeaderNavProps {}

function HeaderNav_(props: HeaderNavProps, ref: HTMLElementRefOf<"div">) {
  return (
    <nav
      {...props}
      className={clsx(props.className, "font-sans font-semibold")}
    >
      <DesktopMenu />
      <MobileMenu />
    </nav>
  );
}

const HeaderNav = React.forwardRef(HeaderNav_);
export default HeaderNav;
