export const producers = {
  name: 'producer',
  label: 'Producteurs',
  label_singular: 'Producteur',
  folder: 'content/producers',
  create: true,
  slug: '{{firstname}}-{{lastname}}_{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}',
  fields: [
    { label: 'ID', name: 'id', widget: 'ncw-id' },
    { label: 'Nom', name: 'lastname', widget: 'string', required: true },
    { label: 'Prénom', name: 'firstname', widget: 'string', required: true },
    { label: 'Bio', name: 'biography', widget: 'markdown', required: true },
    { label: 'Activité', name: 'activity', widget: 'string', required: true },
    { label: 'Adresse', name: 'address', widget: 'string', required: false },
    { label: 'Code postal', name: 'postcode', widget: 'string', required: false },
    { label: 'Ville', name: 'city', widget: 'string', required: false },
    { label: 'Téléphone', name: 'phone', widget: 'string', required: false },
    { label: 'Email', name: 'email', widget: 'string', required: false },
    {
      label: 'Photo de profil',
      name: 'photoUrl',
      widget: 'image',
      media_folder: '/{{media_folder}}/images',
      public_folder: '{{public_folder}}/images',
      choose_url: false,
      media_library: { allow_multiple: false },
      required: true,
    },
    {
      label: 'Contrat(s)',
      name: 'contracts',
      widget: 'list',
      field: {
        label: 'Nom du contrat',
        name: 'slug',
        widget: 'relation',
        collection: 'contract',
        search_fields: ['title'],
        value_field: '{{slug}}',
        display_fields: ['title'],
      },
    },
  ],
};
