export const recipes = {
  name: 'recipe',
  label: 'Recettes',
  label_singular: 'Recette',
  folder: 'content/recipes',
  create: true,
  slug: '{{slug}}-{{id}}',
  fields: [
    { label: 'ID', name: 'id', widget: 'ncw-id' },
    { label: 'Titre', name: 'title', widget: 'string', required: true },
    { label: 'Description', name: 'description', widget: 'string', required: true },
    { label: 'Auteur', name: 'author', widget: 'string', required: true },
    { label: 'Date de publication', name: 'date', widget: 'datetime', required: true },
    {
      label: 'Temps de préparation (en minutes)',
      name: 'prepTime',
      widget: 'number',
      required: true,
    },
    {
      label: 'Temps de cuisson (en minutes)',
      name: 'cookTime',
      widget: 'number',
      required: true,
    },
    { label: 'Nombre de personnes', name: 'yields', widget: 'number', required: true },
    {
      label: "Liste d'ingrédients",
      label_singular: 'Ingrédient',
      name: 'ingredients',
      widget: 'list',
      field: { label: 'Ingrédient', name: 'ingredient', widget: 'string' },
      required: true,
    },
    {
      label: 'Instructions',
      label_singular: 'Instruction',
      name: 'instructions',
      widget: 'list',
      field: { label: 'Ingrédient', name: 'ingredient', widget: 'string' },
      required: true,
    },
    {
      label: 'Photo',
      name: 'photoUrl',
      widget: 'image',
      media_folder: '/{{media_folder}}/images',
      public_folder: '{{public_folder}}/images',
      choose_url: false,
      media_library: { allow_multiple: false },
      required: true,
    },
  ],
};
