// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicFooter,
  DefaultFooterProps,
} from "./plasmic/amap_website/PlasmicFooter";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

import { LinkWrapper } from "components";

export interface FooterProps extends DefaultFooterProps {}

function Footer_(props: FooterProps, ref: HTMLElementRefOf<"div">) {
  return (
    <PlasmicFooter
      {...props}
      contactFormLink={{ render: LinkWrapper }}
      homeLink={{ render: LinkWrapper }}
      sitemapLink={{ render: LinkWrapper }}
      legalLink={{ render: LinkWrapper }}
    />
  );
}

const Footer = React.forwardRef(Footer_);
export default Footer;
