// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicFooter,
  DefaultFooterProps,
} from "./plasmic/amap_website/PlasmicFooter";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

import { LinkWrapper } from "components";
import { Footer } from "lib/netlify-types";

export interface FooterProps extends DefaultFooterProps {
  data: Footer;
}

function Footer_(
  { data, ...props }: FooterProps,
  ref: HTMLElementRefOf<"div">
) {
  return (
    <PlasmicFooter
      {...props}
      homeLink={{ render: LinkWrapper }}
      sitemapLink={{ render: LinkWrapper }}
      legalLink={{ render: LinkWrapper }}
      creditsLink={{ render: LinkWrapper }}
      address={data.address}
      postCode={data.postcode}
      city={data.city}
      schedule={data.schedule}
      email={{
        render: (props, Component) => (
          <a href={`mailto:${data.email}`} className={props.className}>
            {data.email}
          </a>
        ),
      }}
      phone={{
        render: (props, Component) => (
          <a href={`tel:${data.phone}`} className={props.className}>
            {data.phone}
          </a>
        ),
      }}
    />
  );
}

const Footer = React.forwardRef(Footer_);
export default Footer;
