// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7CzphteDn95cERg7nN7EAF
// Component: euVZPj_gwz
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_amap_website.module.css"; // plasmic-import: 7CzphteDn95cERg7nN7EAF/projectcss
import sty from "./PlasmicBonjourPage.module.css"; // plasmic-import: euVZPj_gwz/css

export type PlasmicBonjourPage__VariantMembers = {};

export type PlasmicBonjourPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicBonjourPage__VariantsArgs;
export const PlasmicBonjourPage__VariantProps = new Array<VariantPropType>();

export type PlasmicBonjourPage__ArgsType = {};
type ArgPropType = keyof PlasmicBonjourPage__ArgsType;
export const PlasmicBonjourPage__ArgProps = new Array<ArgPropType>();

export type PlasmicBonjourPage__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultBonjourPageProps {}

function PlasmicBonjourPage__RenderFunc(props: {
  variants: PlasmicBonjourPage__VariantsArgs;
  args: PlasmicBonjourPage__ArgsType;
  overrides: PlasmicBonjourPage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBonjourPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBonjourPage__VariantsArgs;
    args?: PlasmicBonjourPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBonjourPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBonjourPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBonjourPage__ArgProps,
      internalVariantPropNames: PlasmicBonjourPage__VariantProps
    });

    return PlasmicBonjourPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBonjourPage";
  } else {
    func.displayName = `PlasmicBonjourPage.${nodeName}`;
  }
  return func;
}

export const PlasmicBonjourPage = Object.assign(
  // Top-level PlasmicBonjourPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBonjourPage
    internalVariantProps: PlasmicBonjourPage__VariantProps,
    internalArgProps: PlasmicBonjourPage__ArgProps
  }
);

export default PlasmicBonjourPage;
/* prettier-ignore-end */
