// CMS config that has to be converted to yaml, read more:
// https://www.marcveens.nl/posts/netlify-cms-generate-config-yml
// import { CmsConfig, CmsCollection, CmsField, CmsFieldBase } from 'netlify-cms-core';
import fs from 'fs';
import path from 'path';
import yaml from 'yaml';

// const defaultMetaFields: CmsField[] = [
//   { label: 'Title', name: 'title', widget: 'string' },
//   { label: 'Page URL', name: 'url', widget: 'string' },
//   {
//     label: 'Meta',
//     name: 'meta',
//     widget: 'object',
//     fields: [
//       { label: 'Title', name: 'title', widget: 'string' },
//       { label: 'Description', name: 'description', widget: 'string' },
//     ],
//   },
// ];

const metadata = {
  name: 'metadata',
  label: 'Informations du site',
  files: [
    {
      name: 'contact',
      label: 'Informations de contact',
      file: 'content/site_metadata/contact.md',
      fields: [
        { label: 'Téléphone', name: 'phone', widget: 'string', required: true },
        { label: 'Email', name: 'email', widget: 'string', required: true },
      ],
    },
    {
      name: 'address',
      label: 'Adresse',
      file: 'content/site_metadata/address.md',
      fields: [
        { label: 'Adresse', name: 'address', widget: 'string', required: true },
        { label: 'Code postal', name: 'postcode', widget: 'string', required: true },
        { label: 'Ville', name: 'city', widget: 'string', required: true },
      ],
    },
    {
      name: 'amap',
      label: "Informations de l'AMAP",
      file: 'content/site_metadata/amap.md',
      fields: [
        { label: "Nom de l'AMAP", name: 'name', widget: 'string', required: true },
        { label: 'Horaires', name: 'schedule', widget: 'string', required: false },
      ],
    },
  ],
};

const pages = {
  name: 'pages',
  label: 'Pages',
  files: [
    {
      label: 'Adhésion',
      name: 'membership',
      file: 'content/pages/membership.md',
      fields: [
        { label: 'Description', name: 'description', widget: 'markdown', required: true },
        {
          label: 'Document',
          name: 'documentPath',
          widget: 'file',
          media_folder: '/{{media_folder}}/files',
          public_folder: '{{public_folder}}/files',
          media_library: {
            name: 'medias',
            config: { allow_multiple: false, choose_url: false },
          },
          required: true,
        },
      ],
    },
    {
      label: 'Charte des AMAP',
      name: 'convention',
      file: 'content/pages/convention.md',
      fields: [{ label: 'Contenu', name: 'body', widget: 'markdown', required: true }],
    },
    {
      label: "Statuts de l'association",
      name: 'statutes',
      file: 'content/pages/statutes.md',
      fields: [{ label: 'Contenu', name: 'body', widget: 'markdown', required: true }],
    },
  ],
};

const tutors = {
  name: 'tutor',
  label: 'Tuteurs',
  label_singular: 'Tuteur',
  folder: 'content/tutors',
  create: true,
  slug: '{{id}}',
  fields: [
    { label: 'ID', name: 'id', prefix: 'tutor', widget: 'ncw-id' },
    { label: 'Nom', name: 'lastname', widget: 'string', required: true },
    { label: 'Prénom', name: 'firstname', widget: 'string', required: true },
    { label: 'Contact', name: 'contact', widget: 'string', required: false },
  ],
};

export const config = {
  backend: {
    name: 'git-gateway',
    repo: 'manucoffin/amap-website',
    branch: 'main',
    // identity_url: 'https://amap-goutte-eau.netlify.app/.netlify/identity',
    // gateway_url: 'https://amap-goutte-eau.netlify.app/.netlify/git',
  },
  local_backend: true,
  //   cms_manual_init: true,
  media_folder: 'public/uploads',
  public_folder: '/uploads',
  publish_mode: 'editorial_workflow',
  locale: 'fr',
  slug: { encoding: 'ascii', clean_accents: true },
  collections: [metadata, pages, tutors],
};

// Generate a YAML file that is used to generate types
function main() {
  const configDisclaimer = '# This file is autogenerated\n# Only edit the config.src.ts file\n\n';
  const configString = `${configDisclaimer}${yaml.stringify(config)}`;

  fs.writeFile(path.resolve(__dirname, 'new_config.yml'), configString, (error) => {
    if (error) {
      throw error;
    }
  });
}

main();
