const fs = require('fs');
const path = require('path');
const yaml = require('yaml');
const { createNetlifyTypes } = require('netlify-ts');

import { config } from './config.src';

function capitalize(string) {
  return string[0].toUpperCase() + string.slice(1).toLowerCase();
}

// Generate a YAML file that is used to generate types
function writeYaml() {
  const configDisclaimer = '# This file is autogenerated\n# Only edit the config.src.ts file\n\n';
  const configString = `${configDisclaimer}${yaml.stringify(config)}`;

  fs.writeFileSync(path.resolve(__dirname, 'config.yml'), configString, (error) => {
    if (error) {
      throw error;
    }
  });
}

function writeNetlifyEntities() {
  // The Name attribute of each collection is used to generate the interface name
  const types = createNetlifyTypes('public/admin/config.yml');
  const capitalizedTypes = types.replace(/(?<=interface\s+).*?(?=\s+{)/gs, capitalize);

  fs.writeFileSync('./src/cms/netlify-entities.ts', capitalizedTypes);
}

function main() {
  writeYaml();
  writeNetlifyEntities();
}

main();
