// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7CzphteDn95cERg7nN7EAF
// Component: 8--1DojQth
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_amap_website.module.css"; // plasmic-import: 7CzphteDn95cERg7nN7EAF/projectcss
import sty from "./PlasmicHoverable.module.css"; // plasmic-import: 8--1DojQth/css

import InfoIcon from "./icons/PlasmicIcon__Info"; // plasmic-import: ZMjzg7GYb/icon

export type PlasmicHoverable__VariantMembers = {};

export type PlasmicHoverable__VariantsArgs = {};
type VariantPropType = keyof PlasmicHoverable__VariantsArgs;
export const PlasmicHoverable__VariantProps = new Array<VariantPropType>();

export type PlasmicHoverable__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};

type ArgPropType = keyof PlasmicHoverable__ArgsType;
export const PlasmicHoverable__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicHoverable__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultHoverableProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

function PlasmicHoverable__RenderFunc(props: {
  variants: PlasmicHoverable__VariantsArgs;
  args: PlasmicHoverable__ArgsType;
  overrides: PlasmicHoverable__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    true ? (
      <p.Stack
        as={"div"}
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        hasGap={true}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_tokens,
          sty.root
        )}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <InfoIcon
              className={classNames(projectcss.all, sty.svg__mbiCy)}
              role={"img"}
            />
          ),

          value: args.slot
        })}

        {p.renderPlasmicSlot({
          defaultContents: "Infos",
          value: args.children,
          className: classNames(sty.slotTargetChildren)
        })}
      </p.Stack>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHoverable__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHoverable__VariantsArgs;
    args?: PlasmicHoverable__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHoverable__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHoverable__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHoverable__ArgProps,
      internalVariantPropNames: PlasmicHoverable__VariantProps
    });

    return PlasmicHoverable__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHoverable";
  } else {
    func.displayName = `PlasmicHoverable.${nodeName}`;
  }
  return func;
}

export const PlasmicHoverable = Object.assign(
  // Top-level PlasmicHoverable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHoverable
    internalVariantProps: PlasmicHoverable__VariantProps,
    internalArgProps: PlasmicHoverable__ArgProps
  }
);

export default PlasmicHoverable;
/* prettier-ignore-end */
