// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7CzphteDn95cERg7nN7EAF
// Component: 8XNt3BOtDt
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: dTKTvnUQf8/component
import AmapAdvantageBlock from "../../home/AmapAdvantageBlock"; // plasmic-import: IPO3E1dkvS/component
import AmapDescriptionBlock from "../../home/AmapDescriptionBlock"; // plasmic-import: uZnVkj7Gzvz/component
import ListItem from "../../ListItem"; // plasmic-import: 6y2iAxc2rc/component

import { useScreenVariants as useScreenVariantshaBl5ZeVufY } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HABl5zeVufY/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_amap_website.module.css"; // plasmic-import: 7CzphteDn95cERg7nN7EAF/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 8XNt3BOtDt/css

import ArrowDownsvgIcon from "./icons/PlasmicIcon__ArrowDownsvg"; // plasmic-import: vwon0ZYL0/icon
import DottedLineIcon from "./icons/PlasmicIcon__DottedLine"; // plasmic-import: yxDDmV5N_/icon
import DottedLine2Icon from "./icons/PlasmicIcon__DottedLine2"; // plasmic-import: bDG5ZCgOH/icon
import BrushIcon from "./icons/PlasmicIcon__Brush"; // plasmic-import: 7RNqhMDlZ/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  h1?: p.Flex<"h1">;
  scrollDownButton?: p.Flex<"a"> & Partial<LinkProps>;
  sectionAvantages?: p.Flex<"div">;
  sectionCommentCaMarche?: p.Flex<"div">;
  sectionValeurs?: p.Flex<"div">;
  columns?: p.Flex<"div">;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshaBl5ZeVufY()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"AMAP de la Goutte d'Eau - Accueil"}</title>
        <meta
          key="og:title"
          property="og:title"
          content={"AMAP de la Goutte d'Eau - Accueil"}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__ssu9H)}>
              <Header
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames("__wab_instance", sty.header)}
              />

              <div className={classNames(projectcss.all, sty.freeBox__kGeKe)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Des paniers "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"bio"}
                    </span>
                    <React.Fragment>{"\npour soutenir\nles "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"producteurs locaux"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </h1>

                <p.PlasmicLink
                  data-plasmic-name={"scrollDownButton"}
                  data-plasmic-override={overrides.scrollDownButton}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.scrollDownButton
                  )}
                  component={Link}
                  href={"#qu-est-ce-qu-une-amap" as const}
                  platform={"nextjs"}
                >
                  {"Découvrir l'AMAP"}
                </p.PlasmicLink>

                <ArrowDownsvgIcon
                  className={classNames(projectcss.all, sty.svg__ttGn0)}
                  role={"img"}
                />
              </div>
            </div>
          ) : null}

          <div
            data-plasmic-name={"sectionAvantages"}
            data-plasmic-override={overrides.sectionAvantages}
            className={classNames(projectcss.all, sty.sectionAvantages)}
          >
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__z4F0F
              )}
            >
              {"Pourquoi adhérer à une AMAP ?"}
            </h2>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__oPxo6)}
            >
              <AmapAdvantageBlock
                className={classNames(
                  "__wab_instance",
                  sty.amapAdvantageBlock__zh6ZX
                )}
              />

              <AmapAdvantageBlock
                className={classNames(
                  "__wab_instance",
                  sty.amapAdvantageBlock__h8O0P
                )}
                description={
                  "En achetant les produits à l’avance, vous assurez une sécurité financière pour les producteurs, ce qui leur permet de pouvoir gérer les aléas de la production plus sereinement."
                }
                image={
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___2JKn)}
                    displayHeight={"128px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"128px" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/amap_website/images/supportIcon.png",
                      fullWidth: 256,
                      fullHeight: 256,
                      aspectRatio: undefined
                    }}
                  />
                }
                title={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vEYzo
                    )}
                  >
                    {"Pour les producteurs"}
                  </div>
                }
              />

              <AmapAdvantageBlock
                className={classNames(
                  "__wab_instance",
                  sty.amapAdvantageBlock__gomOy
                )}
                description={
                  "Les paniers permettent de réduire les emballages, et donc de produire moins de déchets.\nDe plus, en favorisant les circuits court, on limite les émissions de CO2 liées au transport."
                }
                image={
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__bGruj)}
                    displayHeight={"128px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"128px" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/amap_website/images/earthOrganicIcon.png",
                      fullWidth: 256,
                      fullHeight: 256,
                      aspectRatio: undefined
                    }}
                  />
                }
                title={"Pour l’environnement"}
              />

              <AmapAdvantageBlock
                className={classNames(
                  "__wab_instance",
                  sty.amapAdvantageBlock__iQnGn
                )}
                description={
                  "Contrairement aux allées froides et sans âme des supermarchés, la distribution des paniers se fait un cadre chaleureux et convivial, qui permet de renouer le lien entre le producteur et les consommateurs."
                }
                image={
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___5Sdbo)}
                    displayHeight={"128px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"128px" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/amap_website/images/handshakeIcon.png",
                      fullWidth: 256,
                      fullHeight: 256,
                      aspectRatio: undefined
                    }}
                  />
                }
                title={"Pour Le lien social"}
              />

              <AmapAdvantageBlock
                className={classNames(
                  "__wab_instance",
                  sty.amapAdvantageBlock__krZPh
                )}
                description={
                  "En réduisant les intermédiaires, on peut réduire le coût du panier, tout en ayant un prix juste pour le producteur. C’est pourquoi le rapport qualité/prix des paniers est excellent !"
                }
                image={
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__dj2Ni)}
                    displayHeight={"128px" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"128px" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/amap_website/images/pigWalletIcon.png",
                      fullWidth: 256,
                      fullHeight: 256,
                      aspectRatio: undefined
                    }}
                  />
                }
                title={"Pour le porte monnaie"}
              />
            </p.Stack>
          </div>

          <div
            data-plasmic-name={"sectionCommentCaMarche"}
            data-plasmic-override={overrides.sectionCommentCaMarche}
            className={classNames(projectcss.all, sty.sectionCommentCaMarche)}
          >
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__bAjAh
              )}
            >
              {"Comment ça marche ?"}
            </h2>

            <div className={classNames(projectcss.all, sty.freeBox__m5KB9)}>
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wso7)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rheQ5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pzLsd
                      )}
                    >
                      {"1"}
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__jZoo0)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6O2H1
                        )}
                      >
                        {"Adhésion"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gPmse
                        )}
                      >
                        {
                          "Je signe un contrat qui m’engage à acheter les produits de mon choix pour une période donnée."
                        }
                      </div>
                    </div>
                  </p.Stack>

                  {(
                    hasVariant(globalVariants, "screen", "md") ? true : true
                  ) ? (
                    <DottedLineIcon
                      className={classNames(projectcss.all, sty.svg__rJutr)}
                      role={"img"}
                    />
                  ) : null}

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rrAdi)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__l8D23)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__s52Jx
                        )}
                      >
                        {"Production"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yfUPp
                        )}
                      >
                        {
                          "De son côté, le producteur s’engage à assurer la livraison des paniers au prix fixé dans le  contrat."
                        }
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nXa00
                      )}
                    >
                      {"2"}
                    </div>
                  </p.Stack>

                  {(
                    hasVariant(globalVariants, "screen", "md") ? true : true
                  ) ? (
                    <DottedLine2Icon
                      className={classNames(projectcss.all, sty.svg__hxxRp)}
                      role={"img"}
                    />
                  ) : null}

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___1Iy6R)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rdHxr
                      )}
                    >
                      {"3"}
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__kPzSm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tBqhU
                        )}
                      >
                        {"Distribution"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9WRy
                        )}
                      >
                        {
                          "Chaque semaine, je vais récupérer mon panier sur le lieu de distribution."
                        }
                      </div>
                    </div>
                  </p.Stack>
                </p.Stack>
              ) : null}
            </div>
          </div>

          {true ? (
            <div
              data-plasmic-name={"sectionValeurs"}
              data-plasmic-override={overrides.sectionValeurs}
              className={classNames(projectcss.all, sty.sectionValeurs)}
              id={"qu-est-ce-qu-une-amap" as const}
            >
              <div className={classNames(projectcss.all, sty.freeBox__zUc5V)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__recme
                  )}
                >
                  {"Les valeurs des AMAP"}
                </h2>

                <div
                  data-plasmic-name={"columns"}
                  data-plasmic-override={overrides.columns}
                  className={classNames(projectcss.all, sty.columns)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__lx7Kq)}
                  >
                    <AmapDescriptionBlock
                      className={classNames(
                        "__wab_instance",
                        sty.amapDescriptionBlock__w4Wd0
                      )}
                      title={
                        <React.Fragment>
                          <BrushIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__aQwh4
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fZjx
                            )}
                          >
                            {"Solidarité"}
                          </div>
                        </React.Fragment>
                      }
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__jDq5G
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__qvw38
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yXr6H
                            )}
                          >
                            {
                              "Soutien des consommateurs aux producteurs dans les aléas de la production"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__it9PC
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__bAmgX
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ydtI1
                            )}
                          >
                            {
                              "Accompagnement du producteur à l’autonomie, c’est-à-dire la capacité à être maître de ses choix"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li___3Wbqr
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__h3C7
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__smUE
                            )}
                          >
                            {"Appui à l’agriculture paysanne locale"}
                          </div>
                        </ListItem>
                      </li>
                    </AmapDescriptionBlock>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__dw44X)}
                  >
                    <AmapDescriptionBlock
                      className={classNames(
                        "__wab_instance",
                        sty.amapDescriptionBlock__i2I0A
                      )}
                      title={
                        <React.Fragment>
                          <BrushIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__oGhlr
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rPcTa
                            )}
                          >
                            {"Équité"}
                          </div>
                        </React.Fragment>
                      }
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__bcp4K
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__uRg0U
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pp0Gg
                            )}
                          >
                            {
                              "Définition à chaque saison d’un prix équitable entre consommateurs et producteur"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__pza3S
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__edDZu
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aak6H
                            )}
                          >
                            {
                              "Formalisation et respect des contrats entre consommateurs et producteur"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__ewicI
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__t0TuQ
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jbVWn
                            )}
                          >
                            {
                              "Respect des normes sociales par rapport aux employés de l’exploitation, y compris le personnel temporaire"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__cOwJz
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__tfM9R
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___1RGdu
                            )}
                          >
                            {
                              "Aucun intermédiaire entre producteur et consommateurs, pas de produits achetés et revendus par le producteur sans accord des consommateurs"
                            }
                          </div>
                        </ListItem>
                      </li>
                    </AmapDescriptionBlock>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___9K8DV)}
                  >
                    <AmapDescriptionBlock
                      className={classNames(
                        "__wab_instance",
                        sty.amapDescriptionBlock__baYiN
                      )}
                      title={
                        <React.Fragment>
                          <BrushIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xbMB
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vgPmS
                            )}
                          >
                            {"Qualité"}
                          </div>
                        </React.Fragment>
                      }
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__twgBt
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__gWhmR
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xhl5L
                            )}
                          >
                            {
                              "Qualité des produits : gustative, sanitaire, environnementale"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__uTdm1
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__sj1Zw
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cgQhH
                            )}
                          >
                            {
                              "Production respectueuse de la nature, de l’environnement et de l’animal"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__uR0I
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__ody9J
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cGzrY
                            )}
                          >
                            {
                              "Information fréquente du consommateur sur les produits"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__dExx
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__hbA0C
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lSuz7
                            )}
                          >
                            {
                              "Recherche de la transparence dans les actes d’achat, de production, de transformation et de vente des produits agricoles"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__vCnnF
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__gakyC
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__c0Bjv
                            )}
                          >
                            {
                              "Production de dimension humaine adaptée aux types de culture et d’élevage"
                            }
                          </div>
                        </ListItem>
                      </li>
                    </AmapDescriptionBlock>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__idwWv)}
                  >
                    <AmapDescriptionBlock
                      className={classNames(
                        "__wab_instance",
                        sty.amapDescriptionBlock__irrx1
                      )}
                      title={
                        <React.Fragment>
                          <BrushIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dGj1
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zLAxi
                            )}
                          >
                            {"Lien Social"}
                          </div>
                        </React.Fragment>
                      }
                    >
                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__twftI
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__olym6
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___7DUd1
                            )}
                          >
                            {"Proximité du producteur et des consommateurs"}
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__aUane
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem___8LJ5
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__agRkQ
                            )}
                          >
                            {
                              "Participation active des consommateurs à l’AMAP favorisée notamment par la responsabilisation du maximum d’adhérents"
                            }
                          </div>
                        </ListItem>
                      </li>

                      <li
                        className={classNames(
                          projectcss.all,
                          projectcss.li,
                          sty.li__dvJyz
                        )}
                      >
                        <ListItem
                          className={classNames(
                            "__wab_instance",
                            sty.listItem__wuVyi
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sk5Cs
                            )}
                          >
                            {
                              "Sensibilisation des adhérents de l’AMAP aux particularités de l’agriculture paysanne"
                            }
                          </div>
                        </ListItem>
                      </li>
                    </AmapDescriptionBlock>
                  </div>
                </div>
              </div>
            </div>
          ) : null}
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "h1",
    "scrollDownButton",
    "sectionAvantages",
    "sectionCommentCaMarche",
    "sectionValeurs",
    "columns"
  ],
  header: ["header"],
  h1: ["h1"],
  scrollDownButton: ["scrollDownButton"],
  sectionAvantages: ["sectionAvantages"],
  sectionCommentCaMarche: ["sectionCommentCaMarche"],
  sectionValeurs: ["sectionValeurs", "columns"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  h1: "h1";
  scrollDownButton: "a";
  sectionAvantages: "div";
  sectionCommentCaMarche: "div";
  sectionValeurs: "div";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    h1: makeNodeComponent("h1"),
    scrollDownButton: makeNodeComponent("scrollDownButton"),
    sectionAvantages: makeNodeComponent("sectionAvantages"),
    sectionCommentCaMarche: makeNodeComponent("sectionCommentCaMarche"),
    sectionValeurs: makeNodeComponent("sectionValeurs"),
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
